#!/bin/sh

VCS_REF=`git rev-parse --short HEAD`
VERSION=`git ls-remote -t https://github.com/syncthing/syncthing \
    | grep -o 'v[0-9\.]*' \
    | sort -ubt . -k 1,1nr -k 2,2nr -k 3,3r -k 4,4r -k 5,5r \
    | head -n 1 \
    | grep -o '[0-9\.]*'`

echo $VCS_REF
echo $VERSION

docker build \
    --build-arg VCS_REF=$VCS_REF \
    --build-arg VERSION=$VERSION \
    -t $IMAGE_NAME .

docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION
docker push $DOCKER_REPO:$VERSION
